name: Ruby

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['head', '3.4', '3.3', '3.2']
        activesupport: ['main', '8.1.0', '8.0.0', '7.2.0']

    continue-on-error: ${{ matrix.ruby == 'head' || matrix.activesupport == 'main' }}

    env:
      ACTIVESUPPORT_VERSION: ${{ matrix.activesupport }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate Gemfile for test matrix
        run: |
          cat > Gemfile <<EOF
          source "https://rubygems.org"
          gemspec

          $(if [ "${ACTIVESUPPORT_VERSION}" = "main" ]; then
              echo 'gem "activesupport", github: "rails/rails", branch: "main"'
            else
              echo "gem \"activesupport\", \"~> ${ACTIVESUPPORT_VERSION}\""
            fi)
          EOF

      - name: Install dependencies
        run: bundle install --jobs 4

      - name: Run the default task
        run: bundle exec rake
